---
# nix run nixpkgs#mustache-go -- drone.json drone-yaml.mustache > .drone.yml
kind: pipeline
type: exec
name: flake info

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: show flake info
  commands:
  - nix --experimental-features "nix-command flakes" flake show
  - nix --experimental-features "nix-command flakes" flake metadata

- name: run flake checks
  commands:
  - nix --experimental-features "nix-command flakes" flake check --show-trace

---
kind: pipeline
type: exec
name: build amd64 hosts

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:

- name: build thinkpad-x250
  commands:
  - nix build '.#nixosConfigurations.thinkpad-x250.config.system.build.toplevel' --out-link result-thinkpad-x250
  - nix path-info --closure-size -h $(readlink -f result-thinkpad-x250)

- name: upload to binary cache via s3
  commands:
  - nix run 'github:mayniklas/nixos'#s3uploader
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_key
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret

trigger:
  branch:
  - main
  event:
  - cron
  - push
  - pull_request

